# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

display: ":99.0"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true

install:
  - sh -e /etc/init.d/xvfb start

r_binary_packages:
  - boot
  - chron
  - colorspace
  - dichromat
  - digest
  - ggplot2
  - gtable
  - labeling
  - lattice
  - latticeextra
  - mass
  - matrix
  - munsell
  - nlme
  - proto
  - randomfields
  - rcolorbrewer
  - rcpp
  - reshape
  - rgdal
  - scales
  - snow
  - sp
  - stringr
  - tkrplot
  - xts
  - zoo

r_github_packages:
  - s-u/fastshp

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
