# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

sudo: required

env:
  global:
    - DISPLAY=:99.0
    - R_BUILD_ARGS=" "
    - R_CHECK_ARGS="--as-cran"
    - BOOTSTRAP_LATEX="1"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - sh -e /etc/init.d/xvfb start
  - ./travis-tool.sh install_r_binary boot chron circstats colorspace data.table dichromat digest downloader dplyr ggplot2 gtable httr igraph labeling lattice latticeextra knitr magrittr mass matrix munsell nlme proto randomfields raster rcolorbrewer rcpp reshape rgdal scales secr snow sp stringr tkrplot xts zoo
  - ./travis-tool.sh install_github s-u/fastshp jimhester/covr
  - ./travis-tool.sh install_deps

script:
  - travis_wait ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
