# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

cran: http://cran.rstudio.com/

sudo: required

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

r_build_args: " "

r_check_args: "--as-cran"

warnings_are_errors: true

apt_packages:
  - curl
  - latex-xcolor
  - libcurl4-openssl-dev

r_binary_packages:
  - archivist
  - chron
  - circstats
  - colorspace
  - data.table
  - dichromat
  - digest
  - dplyr
  - ggplot2
  - gtable
  - httr
  - igraph
  - knitr
  - labeling
  - latticeextra
  - lubridate
  - magrittr
  - munsell
  - proto
  - randomfields
  - raster
  - rcolorbrewer
  - rcpp
  - reshape
  - rgdal
  - scales
  - secr
  - snow
  - sp
  - stringr
  - testthat
  - tkrplot
  - xts
  - zoo

r_github_packages:
  - s-u/fastshp
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls(coverage = print(package_coverage(quiet = FALSE))); devtools::session_info()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
