# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_aptget libx11-dev tcl8.6-dev tk8.6-dev
  - ./travis-tool.sh install_r_binary boot chron colorspace dichromat digest ggplot2 gtable labeling lattice latticeextra mass matrix munsell nlme proto  rcolorbrewer rcpp reshape rgdal scales snow sp stringr xts zoo
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
