name: Eliot McIntire
markdown: redcarpet
pygments: true
baseurl: /SpaDES

domain: predictiveecology.org
author: Eliot McIntire
email: eliot.mcintire@nrcan.gc.ca

google_analytics:
   account: UA-58633549-1

github:
   username: PredictiveEcology

